
-- Generated by ORDS REST Data Services 26.1.1.r1321130
-- Schema: WKSP_HOLAYAKAY  Date: Mon Jun 08 01:49:12 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'holayakay',
      p_auto_rest_auth      => TRUE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'p2p_main',
      p_base_path      => '/p2p_main/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => 'P2P Calling API');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'candidates/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'candidates/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    p2p_api_pkg.add_candidate(:session_id, :candidate, :sdp_mid, :sdp_manced, :out);
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'session/{session_id}/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'session/{session_id}/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
':out := p2p_api_pkg.get_session_json(:session_id);');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'session/{session_id}/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    p2p_api_pkg.update_session_status(:session_id, :status, :out);
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'users/{user_id}',
      p_priority       => 1,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

   ORDS.DEFINE_HANDLER(
       p_module_name    => 'p2p_main',
       p_pattern        => 'users/{user_id}',
       p_method         => 'GET',
       p_source_type    => 'plsql/block',
       p_mimes_allowed  => NULL,
       p_comments       => NULL,
       p_source         =>
'BEGIN
    :fcm_token := p2p_api_pkg.get_user_fcm_token(:user_id);
    :name := p2p_api_pkg.get_user_name(:user_id);
END;');

   ORDS.DEFINE_HANDLER(
       p_module_name    => 'p2p_main',
       p_pattern        => 'users/{user_id}',
       p_method         => 'PUT',
       p_source_type    => 'plsql/block',
       p_mimes_allowed  => NULL,
       p_comments       => NULL,
       p_source         =>
'BEGIN
    p2p_api_pkg.register_user(:user_id, :name, :fcm_token, :out);
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'sdp/offers/{session_id}/',
      p_priority       => 1,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'sdp/offers/{session_id}/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
':out := p2p_api_pkg.get_offer_json(:session_id);');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'sdp/answers/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'sdp/answers/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    p2p_api_pkg.save_answer(:session_id, :sdp, :out);
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'calls/',
      p_priority       => 1,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'calls/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_session_id VARCHAR2(50);
BEGIN
    p2p_api_pkg.initiate_call(:caller_id, :callee_id, l_session_id, :out);
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'health/',
      p_priority       => 1,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'health/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'-- :status := p2p_api_pkg.health_check;

BEGIN
    -- Устанавливаем заголовок ответа
    -- OWA_UTIL.MIME_HEADER(''''application/json'''', TRUE);
    
    -- Выводим JSON-строку из вашей функции в HTTP-тело
    -- HTP.P(p2p_api_pkg.health_check);

    -- HTP.P(''{"status":"ok","timestamp":"'' || TO_CHAR(CURRENT_TIMESTAMP, ''YYYY-MM-DD HH24:MI:SS'') || ''"}'');

    -- :contentType := ''''application/json; charset=utf-8'''';
    
    -- Просто выплевываем вашу функцию в поток
    HTP.P(p2p_api_pkg.health_check);


END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'sdp/answers/{session_id}/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'sdp/answers/{session_id}/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
':out := p2p_api_pkg.get_answer_json(:session_id);');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'calls/{session_id}/',
      p_priority       => 1,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'calls/{session_id}/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
':out := p2p_api_pkg.get_session_json(:session_id);');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'calls/{session_id}/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    p2p_api_pkg.update_session_status(:session_id, :status, :out);
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'candidates/{session_id}/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'candidates/{session_id}/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
':out := p2p_api_pkg.get_candidates_json(:session_id);');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'p2p_main',
      p_pattern        => 'sdp/offers/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'p2p_main',
      p_pattern        => 'sdp/offers/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    p2p_api_pkg.save_offer(:session_id, :sdp, :out);
END;');

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;